[package]
name = "opendp_proposal"
version = "0.1.0"
authors = ["Shoeboxam <shoeboxam@gmail.com>"]
edition = "2018"

[dependencies]
#rand = "0.7.3"
num = "0.3.0"
#serde_json = "1.0"
thiserror = "1.0.20"
derive_more = "0.99.9"


[lib]
name = "opendp_proposal"
crate-type = ["rlib", "cdylib"]
