[package]
name = "opendp_test_app"
version = "0.1.0"
authors = ["Shoeboxam <shoeboxam@gmail.com>"]
edition = "2018"

[dependencies]
opendp = {path = "../opendp"}
opendp-derive = {path = "../opendp-derive"}
noisy_float = "0.1.13"